AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - example/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/**.rb

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Exclude:
    - lib/emrb/server.rb

Style/Documentation:
  Exclude:
    - lib/emrb/server.rb
    - spec/**/*
